title: Brian C. Prest

email: prest@rff.org
twitter_username: bprest
github_username: bprest
logo: /assets/img/prest_headshot.png
description: Economist, Resources for the Future
show_downloads: false
google_analytics:

theme: jekyll-theme-minimal
